---
- name: Kubernetes cluster deploy
  hosts: all
  roles:
    - role: containerd
      become: yes
    - role: kubernetes
      become: yes
    - role: crictl
      become: yes
#
#
- name: Controlplane initialization
  hosts: controlplane
  vars:
    stdout_callback: yaml
  roles:
    - role: controlplane
    - role: helm

#- name: Joining nodes
#  hosts: workernodes
#  roles:
#    - role: workernode
#      become: yes
#

