---
- name: Adding Kubernetes repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/
    src: ../files/kubernetes.repo
    mode: 0644

- name: Kubernetes installation
  ansible.builtin.yum:
    name: "{{item}}"
    state: present
    disable_excludes: kubernetes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable Kubernetes service
  ansible.builtin.service:
    name: kubelet
    enabled: true
    state: started

- name: Disable swap for installation
  ansible.builtin.command: "swapoff -a"

- name: Check if swap is already disabled
  ansible.builtin.command: cat /etc/fstab
  register: fstab
  

- name: Remove swap permanently
  ansible.builtin.replace:
    path: /etc/fstab
    regexp:  '/dev/mapper/{{item}}-swap'
    replace: '#/dev/mapper/{{item}}-swap'
  with_items:
    - centos9s
    - centos8s
  when: '"#/dev/mapper/centos9s-swap" not in fstab.stdout' 
