---
- name: Download  Crictl
  ansible.builtin.get_url: 
    url:  "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{clicrtllastv}}/crictl-v{{clicrtllastv}}-linux-amd64.tar.gz"
    dest: /usr/local/bin

- name: Untar wordpress
  ansible.builtin.unarchive:
    dest: /usr/local/bin/
    src: "/usr/local/bin/crictl-v{{clicrtllastv}}-linux-amd64.tar.gz"
    remote_src: yes
    owner: root
    group: root
    mode: 0744
  notify: crictl cleanup
