---
- name: Loading required kernel modules
  community.general.modprobe:
    name: "{{item}}"
    persistent: present
  with_items:
    - overlay
    - br_netfilter

- name: Setting kernel parameters for Kubernetes networking
  ansible.builtin.copy:
    dest: /etc/sysctl.d/
    src: ../files/kubernetes-cri.conf
    mode: 0644
  notify: Reload systemctl 

- name: Add repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Containerd installation
  ansible.builtin.yum:
    name: containerd.io
    state: present

- name: Enable containerd
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: yes

- name: Configuring containerd
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    src: ../files/config.toml
    mode: 0644
  notify: Restart containerd

- name: Force configuration apply
  ansible.builtin.meta: flush_handlers